=== TomasMBMatos/tp1/out/production/tp1/xml/banco.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT banco (clientes)>
<!ELEMENT clientes (cliente*)>
<!ELEMENT  cliente (conta)*>
<!ATTLIST cliente
        user CDATA #REQUIRED
        password CDATA #REQUIRED>
<!ELEMENT conta (saldo, numero, cc, data*, movimentos*)>
<!ATTLIST conta
        tipo CDATA #REQUIRED
        nome CDATA #REQUIRED
        apelido CDATA #REQUIRED>
<!ELEMENT saldo (#PCDATA)>
<!ELEMENT cc (#PCDATA)>
<!ELEMENT numero (#PCDATA)>
<!ELEMENT data (#PCDATA)>
<!ELEMENT movimentos (movimento)*>
<!ELEMENT movimento (#PCDATA)>
<!ATTLIST movimento
        tipo CDATA #REQUIRED
        data CDATA #REQUIRED
        valor CDATA #REQUIRED>

=== TomasMBMatos/tp1/tp4/src/xml/banco.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE banco SYSTEM "banco.dtd">
<banco>
    <clientes>
        <cliente password="1" user="admin">
            <conta apelido="conta" nome="multibanco" tipo="Multibanco">
                <saldo>190.0</saldo>
                <numero>5113372780907934</numero>
                <cc>123123123</cc>
                <movimentos>
                </movimentos>
            </conta>
        </cliente>
    </clientes>
</banco>
