=== TomasMBMatos/tp1/Gestao Banco/src/xml/banco.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT banco (clientes, numeroConta)>
<!ELEMENT clientes (cliente*)>
<!ELEMENT  cliente (conta)*>
<!ATTLIST cliente
        user CDATA #REQUIRED
        password CDATA #REQUIRED>
<!ELEMENT numeroConta (numero)*>
<!ELEMENT numero (#PCDATA)>
<!ELEMENT conta EMPTY>
<!ATTLIST conta
        numero CDATA #REQUIRED
        saldo CDATA #REQUIRED
        nome CDATA #REQUIRED
        apelido CDATA #REQUIRED
        cc CDATA #REQUIRED>

=== TomasMBMatos/tp1/Gestao Banco/src/xml/banco.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE banco SYSTEM "banco.dtd">
<banco>
    <clientes>
        <cliente user="User1" password="teste123">
            <conta numero="123456789" saldo="100" nome="Pedro" apelido="Costa" cc="123456789"/>
            <conta numero="987654321" saldo="200" nome="Pedro" apelido="Costa" cc="123456789"/>
        </cliente>
    </clientes>
    <numeroConta>
        <numero>
            123456789
        </numero>
        <numero>
            987654321
        </numero>
    </numeroConta>
</banco>
